### ISSUE TITLE
site not builded properly by hugo

### ISSUE THREAD

**Issue by ghost** [LordMathis/hugo-theme-nix#11]
at first when I run "hugo server" it works fine on my machine. But when I compile the project by running "Hugo" it doesn't compile the site properly. 
Please follow the site in this link. https://github.com/sbmaruf/index
Here is my site https://sbmaruf.github.io/index/

You will get the compiled sites in "Docs" folder. I have added publishDir="docs" 
in the config.toml file to compile the project into Docs folder.
[Don't worry I have also tried without publishing the project into Docs folder. It didn't work]

Finally a new problem occurred. When I exit my first server on my pc and again call "hugo server" this time the image does not appear. [here is the screen shot of my site at my PC](https://screenshot.net/o443so9). But if I update "About" section of the configure file while the server is on it works.
Here is the message on the terminal while I run "hugo server".
```
ERROR 2017/06/14 05:46:40 port 1313 already in use, attempting to use an available port
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
5 regular pages created
24 other pages created
0 non-page files copied
9 paginator pages created
2 categories created
6 tags created
total in 17 ms
Watching for changes in /home/sbmaruf/index/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:58533/index/ (bind address 127.0.0.1)
Press Ctrl+C to stop

```

**Comment by lordmathis** [comment]
Hi

I looked at your site in Chrome dev tools. In console you get two errors. One is for your image 7.png and the other is for nix.css. 7.png points to `https://sbmaruf.github.io/7.png` but in reality, it should be in `https://sbmaruf.github.io/index/7.png`. Similarly, nix.css points to `https://geeklaunch.github.io/index/css/nix.css` which is not even your website. 

I'm not familiar with how to host hugo website on github pages so I don't know what exactly and where needs fixing but it shouldn't be too hard. Fixing those links should resolve your issue.
