### ISSUE TITLE
Empty ProfilePicture-property issue

### ISSUE THREAD

**Issue by ezschemi** [LordMathis/hugo-theme-nix#16]
When leaving the ProfilePicture-property empty, the resulting webpage will display a small oval with "profile-picture" in it. It would be better to skip that part of the HTML when it is not set. This can be done with:

```
{{ with .Site.Params.ProfilePicture }}
<div class="row">
    <div class="col-sm-3 col-centered">
        <img alt="profile-picture" class="img-responsive img-circle user-picture" src="{{ .Site.Params.ProfilePicture }}">
    </div>
</div>
{{ end }}
```

in layouts/index.html

**Comment by lordmathis** [comment]
That makes sense. If you want you can submit a pull request and I'll merge it.
