### ISSUE TITLE
Strikethrough on hover post title

### ISSUE THREAD

**Issue by nickanderson** [LordMathis/hugo-theme-nix#31]
Is it intentional that hovering a post title should make it strikethrough?

I was able to override it by editing static/css/nix.css and adding 

```
a:hover {
	text-decoration: none;
}
```

But unsure if it was intentional.

**Comment by lordmathis** [comment]
It's not intentional. It should be underlined on hover (standard link hover behaviour, nothing special). I cannot reproduce this on my end. Can you provide some screenshots? Is there a possibility that some extension is modifying the CSS?

**Comment by nickanderson** [comment]
A few pixels lower and it would be an underline.

![2017-11-29_selection_002](https://user-images.githubusercontent.com/202896/33396599-a5022aac-d50e-11e7-84b4-807ada6517fe.png)

Ive seen this in chrome and firefox. A friend noted the same. I doubt it is an extension.

**Comment by lordmathis** [comment]
Hmm. That's weird. 

I cannot reproduce it. It looks perfectly normal on my end. Both on Firefox and Chrome. Try looking at the computed CSS styles in Chrome dev tools. Maybe there will be some clues

**Comment by nickanderson** [comment]
OK. Ill close this out then since it doesn't affect others.

Thanks!

**Comment by lordmathis** [comment]
Hi,
 I recently encountered this problem on another project and it seems to be a problem with the font Firefox combination. Here's a relevant StackOverflow [link](https://stackoverflow.com/questions/23991699/underline-text-decoration-is-crossing-through-the-imported-font-used-in-firefox).
