### ISSUE TITLE
Is there a way to rearrange the order in which social media buttons appear?

### ISSUE THREAD

**Issue by jarhill0** [LordMathis/hugo-theme-nix#32]
I have four items: Twitter, GitHub, Telegram, and email, and the theme shows them in that order. Is there a way I can get them to show up in a different order? Thanks.

**Edit**: I see that I could edit this file: https://github.com/LordMathis/hugo-theme-nix/blob/cab3017cbc9b2b285939b2763cd61d20eeb9f7f1/layouts/index.html#L27-L59 but I'm wondering if there's a way to do it through a config file.

**Comment by lordmathis** [comment]
Hi, the correct file to edit is this file: 
https://github.com/LordMathis/hugo-theme-nix/blob/master/layouts/partials/social.html

I think you have pointed to some older commit before the social links were separated to their own partial. Editing the file is the only way to change order for now.

**Comment by jarhill0** [comment]
Thanks. You're right, I linked to an old commit. Not sure why I did that.
