### ISSUE TITLE
Submenu

### ISSUE THREAD

**Issue by fgallaire** [LordMathis/hugo-theme-nix#47]
I don't succeed to add a submenu item.

I use "identifier" in the parent and "parent" in the children, but nothing happens.

**Comment by lordmathis** [comment]
Can you post the relevant part of your config?

**Comment by fgallaire** [comment]
https://f.gallai.re
```
  [[menu.header]]
    identifier = "layout"
    name = "Layouts"
    weight = 1
    url = "/layouts"
  [[menu.header]]
    parent = "layout"
    name = "Viet US"
    url = "/viet-us"
  [[menu.header]]
    parent = "layout"
    name = "QĐERTY"
    url = "/qderty"
```

**Comment by fgallaire** [comment]
@LordMathis am I doing something wrong ?

**Comment by lordmathis** [comment]
I finally had time to look into this. I copied the part of the config into example site config and started the server. The submenu shows as it should, so you are probably doing something wrong. Try updating Hugo and rerender the website

**Comment by lordmathis** [comment]
Closing this as it doesn't seem to be an issue with the theme
