### ISSUE TITLE
css is not working

### ISSUE THREAD

**Issue by belikesuraj** [LordMathis/hugo-theme-nix#6]
when I upload contents from public directory to github, site is not rendering properly, css is missing out there

**Comment by lordmathis** [comment]
You need to be a bit more specific. What exact steps are you doing? Are you following the instructions from README?

**Comment by belikesuraj** [comment]
it seems that browsers are blocking some contents while on https

**Comment by lordmathis** [comment]
Have you tried different themes? It might be that your config isn't quite right. I have https on my website that uses this theme and it works just fine

**Comment by lordmathis** [comment]
Any news on this? Did you make it work? I'm closing this issue as it's not a problem with the theme itself
