### ISSUE TITLE
Request: Add support for YouTube and Soundcloud social links

### ISSUE THREAD

**Issue by meerasndr** [LordMathis/hugo-theme-nix#65]
I understand that this is a developer focused theme. But, some devs do have YouTube channels and music on Soundcloud (algorithmic and otherwise!). Please consider adding support for these two social links. Thanks!

**Comment by lordmathis** [comment]
Sure but I'm not really sure when I'll have time for that. You can submit a PR if you want and I'll merge it

**Comment by meerasndr** [comment]
Thank you.

**Comment by odalabasmaz** [comment]
Hi @LordMathis, just send a [PR](https://github.com/LordMathis/hugo-theme-nix/pull/66) for it;
