### ISSUE TITLE
.Now will be deprecated with Hugo v0.20

### ISSUE THREAD

**Issue by digitalcraftsman** [LordMathis/hugo-theme-nix#7]
`.Now` will be deprecated replaced with the `now` template function in Hugo v0.20 which eventually will be released on Monday. It's likely that the deprecation will cause builds to fail.

**Comment by lordmathis** [comment]
Thanks for the info. I've updated the theme https://github.com/LordMathis/hugo-theme-nix/commit/a4ea546d5d76d6030ddaa12294f238be3e9327d1
