### ISSUE TITLE
Supported Hugo version

### ISSUE THREAD

**Issue by dfranco** [LordMathis/hugo-theme-nix#78]
Hello,

Could someone tell me which version of Hugo is supported with this theme ?

Using latest Hugo version (0.107.0) fail on my side with the error below

```
ERROR 2023/01/25 07:53:34 render of "page" failed: "/src/themes/hugo-theme-nix/layouts/_default/single.html:11:11": execute of template failed: template: _default/single.html:11:11: executing "_default/single.html" at <partial "header.html" .>: error calling partial: "/src/themes/hugo-theme-nix/layouts/partials/header.html:11:9": execute of template failed: template: partials/header.html:11:9: executing "partials/header.html" at <.RSSLink>: can't evaluate field RSSLink in type *hugolib.pageState
```

Thanks for your help

**Comment by lordmathis** [comment]
Thanks for reporting the issue. My guess is that this is not a problem with new Hugo version but rather PR #77 which I merged few days ago. Can you try it with a commit before this PR?

**Comment by dfranco** [comment]
> Thanks for reporting the issue. My guess is that this is not a problem with new Hugo version but rather PR #77 which I merged few days ago. Can you try it with a commit before this PR? 

It works now, thanks for your feedback 👍

**Comment by dfranco** [comment]
I will probably create a PR to update the README @LordMathis.

I'm closing this one as your feedback helped me to solve the issue.
Thanks again
