### ISSUE TITLE
Request for GnuPG keyserver update

### ISSUE THREAD

**Issue by michael-valdron** [LordMathis/hugo-theme-nix#81]
# Description

As a maintainer of a Hugo site using the Nix theme, I would like to include all social links pointing to all of the relevant sources. Being that I have a GPG key pairing for identity I would like to use the [GnuPG fingerprint](https://github.com/LordMathis/hugo-theme-nix/blob/b4735abcfe60609d78282b1b6da876dea1b735e8/layouts/partials/social.html#L1) field to share my public key.

The current keyserver used by this theme is no longer active. Could be the result of the recent GDPR takedowns of keyserver pools in the EU such as what happened to [sks-keyservers.net](https://web.archive.org/web/20220119094712/https://www.sks-keyservers.net/).

# Solution

Currently, I have changed this keyserver host to use [keys.openpgp.org](https://keys.openpgp.org) on my [folk](https://github.com/michael-valdron/hugo-theme-nix/blob/e74eceba52e2bfd6ea7ebdaf367dd3332f126b4e/layouts/partials/social.html#L2) of the Nix theme. If this is an acceptable change, I can open a PR for provide this change to the user base using Nix.

**Comment by lordmathis** [comment]
Hi @michael-valdron, looks good to me, you can open a PR. Please update also README with the link to new keyserver in comment.
